### ISSUE TITLE
Out of Box Failure: window is not defined

### ISSUE THREAD

**Issue by rajadain** [CrystallizeAPI/crystallize-nextjs-boilerplate#92]
Hello,

Thank you for creating this resource, it is very educational and really promising!

As I'm trying to learn it, I'm seeing some failures out of the box. For example, if I run the following:

```console
$ npx @crystallize/cli test && cd test && npm install && npm run build
```

and choose all the default options:

```
 All right, Next.js it is
 In folder ./test
 Using Crystallize tenant furniture
 In a single language
 With the demo Service API
```

at this stage:

```
info  - Collecting page data  
[=== ] info  - Generating static pages (0/91)
```

I get the following errors:

```
Error occurred prerendering page "/en/[...catalogue]". Read more: https://err.sh/next.js/prerender-error
ReferenceError: window is not defined
    at /Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1725:53
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1742:3)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/main.js:29:22)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
```
```
Error occurred prerendering page "/en/shop". Read more: https://err.sh/next.js/prerender-error
ReferenceError: window is not defined
    at /Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1725:53
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1742:3)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/main.js:29:22)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
```
```
Error occurred prerendering page "/en/shop/plants". Read more: https://err.sh/next.js/prerender-error
ReferenceError: window is not defined
    at /Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1725:53
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/html.js:1742:3)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/rajadain/play/crystallize-nextjs/test/node_modules/imsc/src/main/js/main.js:29:22)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
```
```
> Build error occurred
Error: Export encountered errors on following paths:
	/en/[...catalogue]
	/en/shop
	/en/shop/plants
    at /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/export/index.js:30:1103
    at async /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/build/tracer.js:3:470
    at async /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/build/index.js:39:69
    at async /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/build/tracer.js:3:470
    at async /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/build/index.js:21:731
    at async /Users/rajadain/play/crystallize-nextjs/test/node_modules/next/dist/build/tracer.js:3:470
```

I'm running macOS Big Sur, node `v15.10.0`, and npm `7.6.0` in case that helps. The full output log of the above command is here: [crystallize-cli-failure.txt](https://github.com/CrystallizeAPI/crystallize-nextjs-boilerplate/files/6073168/crystallize-cli-failure.txt)

As you can see, I have not made any changes, just running this out of the box, and seeing this failure. Any help is appreciated.

**Comment by hakonkrogh** [comment]
Hi @rajadain and thanks for the error report. Looks like an issue with the lazy loading of the video player. I'll investigate

**Comment by achadee** [comment]
I turned off the video player to get my instance working

**Comment by hakonkrogh** [comment]
Hi, this should be resolved now as we have released a react-video package that deals with embedding videos from Crystallize: https://www.npmjs.com/package/@crystallize/react-video

**Comment by rajadain** [comment]
Thank you!
